name: run-tests

on: [ push ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: PHPStan Static Analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=512 --error-format=github
